 server:
   port: 8300

 spring:
   main:
     allow-bean-definition-overriding: true
   application:
     name: app-service-member
   redis:
     host: 127.0.0.1
     port: 6379
     jedis:
       pool:
         max-idle: 100
         min-idle: 1
         max-active: 1000
         max-wait: -1
   ###数据库相关连接
   datasource:
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/meite?serverTimezone=UTC

 eureka:
   client:
     service-url:
       defaultZone: http://localhost:8100/eureka/
