 server:
   port: 80

 spring:
   application:
     name: app-mayikt-zuul


 eureka:
   client:
     service-url:
       defaultZone: http://localhost:8100/eureka/

 zuul:
   routes:
     api-a:
       path: /api/weixin/**
       serviceId: app-service-weixin
     api-b:
       path: /api/member/**
       serviceId: app-service-member
